root@0edbbd2c6d38:/app# PYTHONPATH=. pytest tests/core/test_model_perfilusuario.py -v
================================================================ test session starts ================================================================platform linux -- Python 3.12.11, pytest-8.4.1, pluggy-1.6.0 -- /usr/local/bin/python3.12
cachedir: .pytest_cache
django: version: 4.2.7, settings: plataformaweb.settings (from ini)
rootdir: /app
configfile: pytest.ini
plugins: django-4.11.1
collected 1 item

tests/core/test_model_perfilusuario.py::test_user_str PASSED                                                                                  [100%] 

================================================================= 1 passed in 3.34s =================================================================